### ISSUE TITLE
Issue compiling

### ISSUE THREAD

**Issue by egandro** [swaggest/swgui#18]
```
 $ go get github.com/swaggest/swgui/...
go: downloading golang.org/x/net v0.0.0-20200520182314-0ba52f642ac2
go: downloading golang.org/x/text v0.3.2
# github.com/vearutop/statigz
/home/pi/.golib/pkg/mod/github.com/vearutop/statigz@v1.1.1/server.go:265:22: constant 9223372036854775807 overflows int
```

My GO version:  $ go version
go version go1.16.2 linux/arm

**Comment by egandro** [comment]
I sort of got it.

size is set to maxint64. It is a int32 variable - so this causes the overflow.

**Comment by vearutop** [comment]
Thank you for raising this issue, please try latest version `v1.2.2` that should work properly.

**Comment by egandro** [comment]
Thank you!

**Comment by egandro** [comment]
> Thank you for raising this issue, please try latest version `v1.2.2` that should work properly.

Let me do an academic remark. It's 100% academic. We size_t of a file is afaik 64bit also on a 32bit Linux. So you might change the size to the coresponding type of the fstat() function. 

I doubt that this will be ever a problem.
