### ISSUE TITLE
Vulnerable libraries

### ISSUE THREAD

**Issue by andreypozolotinmercedes** [swaggest/swgui#33]
The dependant golang.org/x/text@v0.3.6 library has following security issues:
https://github.com/advisories/GHSA-69ch-w2m2-3vjp
https://github.com/advisories/GHSA-ppp9-7jff-5vj2
Plz consider to upgrade it if possible. 
Thanks

**Comment by vearutop** [comment]
Please try [`v1.6.1`](https://github.com/swaggest/swgui/releases/tag/v1.6.1).
